name: json_serialization_manager
description: pubspec for easier JSON serialization
version: 1.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  json_serializable: ^6.7.1

dev_dependencies:
  build_runner: ^2.4.6
  json_annotation: ^4.8.1